repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.10.1
    hooks:
      - id: check-plists
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.howthegodschill."]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
