---
Description: Downloads the latest version of Docker for Apple Silicon.
Identifier: com.github.howthegodschill.download-arm.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: arm64

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: 'https://desktop\.docker\.com/mac/main/%PLATFORM_ARCH%/[A-Za-z0-9]+/Docker\.dmg'
      result_output_var_name: 'DOWNLOAD_URL'
      url: 'https://docs.docker.com/desktop/release-notes/'

  - Processor: URLDownloader
    Arguments:
      filename: '%NAME%-%ARCHITECTURE%.dmg'
      url: '%DOWNLOAD_URL%'

  - Processor: EndOfCheckPhase

  - Processor: AppDmgVersioner
    Arguments:
      dmg_path: '%pathname%'

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%pathname%/%app_name%'
      requirement: |
        anchor apple generic and identifier "com.docker.docker" and (certificate
        leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6]
        /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists
        */ and certificate leaf[subject.OU] = "9BNSXJN65R")
      deep_verification: true
      strict_verification: true
