Description: |
  1. Downloads the latest version of Docker Desktop and creates a package
  2. Uploads the package to Jamf Pro server
  3. Creates or updates a global Self Service policy
  4. Creates or updates a policy using a custom trigger
  5. Both policies are scoped to all computers
Identifier: com.github.howthegodschill.jamf.Docker-policy
ParentRecipe: com.github.howthegodschill.pkg-arm.Docker
MinimumVersion: "2.3"

Input:
  NAME: "Docker Desktop"
  SHORT_NAME: "DockerDesktop"
  CATEGORY: "Development"
  #PACKAGE_INFO: ""
  PACKAGE_NOTES: "Generated and added via AutoPkg Jamf Uploader process"
  PACKAGE_REPLACE: "False"

# Self Service Policy Settings
  SELF_SERVICE_POLICY_TEMPLATE: "Policy_SelfService.xml"
  SELF_SERVICE_POLICY_NAME: "Self Service - %NAME%"
  SELF_SERVICE_POLICY_FREQUENCY: "Ongoing"
  SELF_SERVICE_POLICY_REPLACE: "true"
  SELF_SERVICE_POLICY_RECON: "true"
  SELF_SERVICE_POLICY_COMMAND_TRIGGER: "jamf policy -event install-docker"

  # Self Service Feature and Categories
  SELF_SERVICE_POLICY_CATEGORY: "%CATEGORY%"

  # Self Service Policy information
  SELF_SERVICE_DISPLAY_NAME: "%NAME% - %version%"
  SELF_SERVICE_PACKAGE_SIZE: "694 MB" #In MB or GB, e.g. 42 MB
  SELF_SERVICE_DESCRIPTION: |
    Download Size: %SELF_SERVICE_PACKAGE_SIZE%
    Version: %version%

    Docker Desktop is collaborative containerization software for developers.

  SELF_SERVICE_ICON: "%NAME%.png"
  SELF_SERVICE_BUTTON_UNINSTALL: "Install"
  SELF_SERVICE_BUTTON_REINSTALL: "Reinstall"

  # Self Service Group Exclusion
  SELF_SERVICE_GROUP_EXCLUSION_1: "INSTALLED - %NAME%"

  # Custom Trigger Policy Information
  POLICY_CATEGORY: "Main Install Policies"
  POLICY_TEMPLATE: "Policy_MainInstall.xml"
  POLICY_NAME: "Install - %NAME%"
  POLICY_FREQUENCY: "Ongoing"
  POLICY_CUSTOM_TRIGGER_NAME: "install-docker"
  POLICY_REPLACE: "true"

  # Set stop criteria
  UPDATE_PREDICATE: "pkg_uploaded != True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_category: "%CATEGORY%"
      pkg_info: "%NAME% %version%"
      pkg_name: "%NAME%-%version%.pkg"
      pkg_notes: "%PACKAGE_NOTES%"
      replace_pkg: "%PACKAGE_REPLACE%"

  - Processor: StopProcessingIf
    Arguments:
      predicate: "%UPDATE_PREDICATE%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%SELF_SERVICE_POLICY_TEMPLATE%"
      policy_name: "%SELF_SERVICE_POLICY_NAME%"
      replace_policy: "%SELF_SERVICE_POLICY_REPLACE%"
      frequency: "%SELF_SERVICE_POLICY_FREQUENCY%"
      icon: "%SELF_SERVICE_ICON%"
      policy_category: "%SELF_SERVICE_POLICY_GENERAL_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%POLICY_TEMPLATE%"
      policy_name: "%POLICY_NAME%"
      replace_policy: "%POLICY_REPLACE%"
      frequency: "%POLICY_FREQUENCY%"
      policy_category: "%POLICY_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfUploaderSlacker
    Arguments:
      PKG_CATEGORY: "%CATEGORY%"