---
Description: Downloads the latest version of Docker for Apple Silicon.
Identifier: com.github.howthegodschill.download-arm.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: arm64
  DOWNLOAD_TYPE: arm64

Process:
  - Processor: com.github.jgstew.SharedProcessors/URLDownloaderPython
    Arguments:
      filename: 'Docker-%ARCHITECTURE%.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: 'https://desktop.docker.com/mac/main/%DOWNLOAD_TYPE%/Docker.dmg'

  - Processor: EndOfCheckPhase
  - Processor: com.github.jgstew.SharedProcessors/StopProcessingIfDownloadUnchanged

  - Processor: AppDmgVersioner
    Arguments:
      dmg_path: '%pathname%'

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/Docker-%ARCHITECTURE%.dmg/Docker.app'
      requirement: |
        anchor apple generic and identifier "com.docker.docker" and (certificate
        leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6]
        /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists
        */ and certificate leaf[subject.OU] = "9BNSXJN65R")
      deep_verification: true
      strict_verification: true
